services:
  - type: web
    name: mlms-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: mlms-backend
          type: web
          property: url

  - type: web
    name: mlms-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8080 